mappings:
- match: "*.*.*.request.*"
  name: "app_request"
  labels:
    service_id: "$1"
    port: "$2"
    protocol: $3
    method: "$4"
- match: "*.*.*.request.unusual.*"
  name: "app_request_unusual"
  labels:
    service_id: "$1"
    port: "$2"
    protocol: $3
    code: "$4"

- match: "*.*.*.requesttime.*"
  name: "app_requesttime"
  labels:
    service_id: "$1"
    port: "$2"
    protocol: $3
    mode: "$4"

- match: "*.*.*.requestclient"
  name: "app_requestclient"
  labels:
    service_id: "$1"
    port: "$2"
    protocol: $3