#############################################
#
# Copyright 2023 Goodrain Co., Ltd.
#
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
#
#############################################

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: rbdplugins.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: RBDPlugin
    listKind: RBDPluginList
    plural: rbdplugins
    singular: rbdplugin
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RBDPlugin is the Schema for the rbdplugins API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RBDPluginSpec defines the desired state of RBDPlugin
            properties:
              display_name:
                description: The alias is the name used for display, and if this
                  field is not set, the name in the metadata will be used
                type: string
              plugin_type:
                enum:
                - JSInject
                - Iframe
                type: string
              frontend_component:
                description: Frontend component name
                type: string
              entry_path:
                description: Entry path for the plugin
                type: string
              plugin_views:
                items:
                  description: PluginView View where the plugin is located
                  enum:
                  - Platform
                  - Team
                  - Application
                  - Component
                  type: string
                type: array
              menu_title:
                description: Menu title for the plugin
                type: string
              route_path:
                description: Route path for the plugin
                type: string
              namespace:
                description: Namespace identifier for the plugin
                type: string
              backend_service:
                description: Backend service address
                type: string
              frontend_service:
                description: Frontend service address
                type: string
            type: object
          status:
            description: RBDPluginStatus defines the observed state of RBDPlugin
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
